apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
        - name: secret-gitlab
      containers:
        - name: spring-boot-app
          image: registry.gitlab.com/rajet/mse_devops:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging