apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: production
spec:
  selector:
    app: spring-boot-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer