apiVersion: v1
kind: Pod
metadata:
  name: maria-db-pod
  namespace: k8s-part-2
  labels: 
    app: mariadb
spec:
  volumes:
    - name: mariadb-volume
      persistentVolumeClaim:
        claimName: mariadb-pvc
  containers:
    - name: mariadb
      image: mariadb:latest
      ports:
        - containerPort: 3306
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_DATABASE
      volumeMounts:
        - name: mariadb-volume
          mountPath: ./mysql