apiVersion: v1
kind: Pod
metadata:
  name: debian-server-pod
  namespace: k8s-part-2
  labels:
    app: debian-server
spec:
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: data-pvc
    - name: script-volume
      configMap:
        name: log-generator-config
        defaultMode: 0755
  containers:
    - name: debian-server
      image: debian:latest
      command: ["/scripts/log-generator.sh"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: script-volume
          mountPath: /scripts
